config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # BandSpaces Routes

  # # Read
  # # route to display all bandspaces for browing
  # get "/band_spaces", to: "bandspaces#index"
  # # route to display a single bandspace and its information
  # get 'band_spaces/:id', to: 'bandspaces#show', as: :bandspace

  # # Create
  # # the create a new bandspace page/form
  # get 'band_spaces/new', to: 'bandspaces#new'
  # # the route to create a new bandspace so it persists
  # post 'band_spaces', to: 'bandspaces#create'

  # # Update
  # # get the edit form for a bandspace
  # get "band_spaces/:id/edit", to: "bandspaces#edit"
  # # perform the actual patch/update of a bandspace
  # patch "band_spaces/:id", to: "bandspaces#update"

  # # Delete
  # # deletes the bandspace :O
  # delete "band_spaces/:id", to: "bandspaces#destroy"
  resources :band_spaces do
    resources :bookings #to be refactored once routes have been finalised
    resources :reviews
  end
  resources :bookings do
    collection do
      get :mine
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/band_space.rb
class BandSpace < ApplicationRecord
  has_one_attached :photo_url
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :address, length: { minimum: 10, maximum: 100 }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :description, presence: true
  validates :description, length: { minimum: 10, maximum: 100 }
  validates :photo_url, presence: true
  validates :user_id, presence: true
  validates :price, presence: true
  validates :price, numericality: { greater_than: 0 }

  include PgSearch::Model

  pg_search_scope :search_by_schema_columns,
    against: [ :name, :description, :address, :capacity, ],
    using: {
      tsearch: { prefix: true }
    }

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :band_space

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :band_space
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, numericality: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings #dependent: destroy 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end

end

app/controllers/band_spaces_controller.rb
class BandSpacesController < ApplicationController
  before_action :set_bandspace, only: [:show, :destroy, :edit, :update]

  def index

    @bandspaces = BandSpace.all
    @markers = @bandspaces.geocoded.map do |bandspace|
      {
        lat: bandspace.latitude,
        lng: bandspace.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {bandspace: bandspace})
      }
    end
    if params[:query].present?
      @bandspaces = BandSpace.search_by_schema_columns(params[:query])
    else
      @bandspaces = BandSpace.all

    end
  end

  def show
    @booking = Booking.new
    @review = Review.new
  end

  def edit
  end

  def update
    @bandspace.update(bandspace_params)
    redirect_to band_space_path(@bandspace)
  end

  def new
    @bandspace = BandSpace.new
  end

  def create
    @bandspace = BandSpace.new(bandspace_params)
    @bandspace.user = current_user
    if @bandspace.save!
      redirect_to band_space_path(@bandspace)
    else
      flash[:bandspace_errors] = @bandspace.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bandspace.destroy
    respond_to do |format|
      format.html { redirect_to band_spaces_url, notice: "Bandspace was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_bandspace
    @bandspace = BandSpace.find(params[:id])
  end

  def bandspace_params
    params.require(:band_space).permit(:name, :description, :price, :address, :capacity, :photo_url)
  end
end

# booking.bandspace = new_booking

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
    redirect_to mine_bookings_path
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @bandspace = BandSpace.find(params[:band_space_id])
    @booking = Booking.new
    # raise
  end

  def mine
    @bookings = Booking.where(params[:user_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @bandspace = BandSpace.find(params[:band_space_id])
    @booking.band_space = @bandspace
    @booking.user = current_user
    # raise
    if @booking.save
      redirect_to band_space_path(@bandspace), notice: 'Booking was successfully created.'
    end
  end

  def destroy
    @booking = Booking.find(params[:booking_id])
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to mine_bookings_path, notice: "booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:band_space_id, :user_id, :date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @bandspaces = BandSpace.first(8)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @bandspace = BandSpace.find(params[:band_space_id])
  end

  def new
    @bandspace = BandSpace.find(params[:band_space_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @bandspace = BandSpace.find(params[:band_space_id])
    @review.band_space = @bandspace
    @review.user = current_user
    if @review.save!
      update_rating(@bandspace)
      redirect_to band_space_path(@bandspace)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:band_space_id, :user_id, :title, :body, :rating)
  end

  def update_rating(bandspace)
    if bandspace.reviews.length != 0
      rating_total = 0
      bandspace.reviews.each do |review|
        rating_total += review.rating
      end
      bandspace.rating = rating_total / bandspace.reviews.length
      bandspace.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/band_spaces/_form.html.erb
<div class="container">
  <%= simple_form_for [@bandspace] do |f| %>
    <%= f.input :photo_url, as: :file %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.error :address %>
    <%= f.input :description %>
    <%= f.input :capacity , as: :numeric, input_html:{ min:"0"} %>
    <%= f.input :price, as: :currency, currency: "£" %>
    <%= f.submit "Submit Bandspace", class: "btn btn-flat" %>
  <% end %>
</div>

app/views/band_spaces/_info_window.html.erb
<%= link_to band_space_path(bandspace) do %>
<div class="popup">
  <% if bandspace.photo_url.key %>
    <%= cl_image_tag bandspace.photo_url.key, class: "card-img-top rounded" %>
  <% else %>
    <img src="<%= bandspace.photo_url.record[:photo_url] %>" class="card-img-top" alt="...">
  <% end %>

  <div class="map-card-body">
    <div class="d-flex justify-content-between">
    <h5 class="card-title">
    <%= bandspace.name %>
    </h5>
    <% if bandspace.rating == nil %>
        <p class="card-text"> <strong> No ratings </strong></p>
      <% else %>
        <p class="card-text">
          <i class="fa-solid fa-star"></i>
          <strong> <%= bandspace.rating%> / 5 </strong>
        </p>
      <% end %>
    </div>
    <div class="price-capacity d-flex justify-content-between">
      <p class="card-text">
        <strong>£ <%= bandspace.price%> </strong>
      </p>
      <p> <i class="fa-sharp fa-solid fa-people-group"></i> Capacity: <%= bandspace.capacity %> </p>
    </div>
</div>
<% end %>

app/views/band_spaces/edit.html.erb
<h2>Edit bandspace Info</h2>
<%= render "form", bandspace: @bandspace %>

app/views/band_spaces/index.html.erb
<div class="container col-9">
  <div>
    <div class="page-title">

      <h1 class="row justify-content-center"> Bandspaces </h1>

        <div class="row justify-content-center">
          <div class="col-sm-8 my-3">
            <%= form_with url: band_spaces_path, method: :get, class: "d-flex my-3" do %>
              <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    placeholder: "Type a keyword"
                %>
              <%= submit_tag "Search", name: "", class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      <div class="d-flex justify-content-center">
        <br>
        <% if user_signed_in? %>
          <p><%= link_to "Add bandspace", new_band_space_path %>
        <% else %>
          <p class="d-none">
        <% end %>
        </p>
         <br>
      </div>
    </div>
    <div class="row d-flex justify-content-evenly">
      <% @bandspaces.reverse.each do |bandspace| %>
        <div class="card" style="width: 18rem;">
        <% if bandspace.photo_url.key %>
          <%= cl_image_tag bandspace.photo_url.key, class: "card-img-top" %>
        <% else %>
          <img src="<%= bandspace.photo_url.record[:photo_url] %>" class="card-img-top" alt="...">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to bandspace.name, band_space_path(bandspace), class: "text-decoration-none" %></h5>
          <p class="card-text"><%= bandspace.address %></p>
          <p class="card-text"> <strong>£ <%= bandspace.price%> </strong></p>
          <% if bandspace.rating == nil %>
            <p class="card-text"> <strong> No ratings </strong></p>
          <% else %>
            <p class="card-text"> <strong> <%= bandspace.rating%> / 5 </strong></p>
          <% end %>
        </div>
      </div>
      <% end  %>
    </div>
  </div>
  <div style="width: 100%; height: 600px;"
       data-controller="map"
       data-map-markers-value="<%= @markers.to_json %>"
       data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<div class="page-end">
</div>

app/views/band_spaces/new.html.erb
<h1>Create a New Bandspace</h1>
<%= render "form", bandspace: @bandspace %>
<% if flash[:bandspace_error] %>
 ["A minimum of ten charters is required"]
<% end %>

app/views/band_spaces/show.html.erb
<div class="container bandspace d-flex flex-column">
  <h2> <%= @bandspace.name %> </h2>
  <div class=" d-flex host-capacity-price">
      <p> Hosted by: <strong><%= @bandspace.user.username %> </strong> </p>
      <p> <i class="fa-sharp fa-solid fa-people-group"></i> Capacity: <strong><%= @bandspace.capacity %></strong></p>
  </div>

  <% if @bandspace.photo_url.key %>
    <%=  cl_image_tag @bandspace.photo_url.key, height: 500 , width: 1000, crop: :fill, class: "image" %>
  <% else  %>
  <img src=<%= @bandspace.photo_url.record[:photo_url]%> style="height: 300;width: 400" class="image">
  <% end %>

  <div class="info-and-booking d-flex justify-content-between col-9">
    <div class="description">
      <p> <%= @bandspace.address %> </p>
      <p> <%= @bandspace.description %> </p>
      <% if @bandspace.user == current_user %>
        <div class="links d-flex">
      <% else %>
        <div class="links d-none">
      <% end %>
        <%= link_to "Edit Bandspace", edit_band_space_path %>
        <%= link_to "Delete Bandspace", band_space_path(@bandspace), data: { turbo_method: :delete} %>
      </div>
    <div class="backspace">
      <%= link_to "Back to Bandspaces", band_spaces_path, class: "btn btn-flat" %>
    </div>
    </div>
    <div class="booking">
      <div class="make-a-booking">
        <div class="form-label-price d-flex justify-content-between">
          <h3>Date</h3>
          <p><strong>£<%= @bandspace.price %></strong> per day </p>
        </div>
        <div class="booking-form my-1">
          <%= render :partial => '/bookings/form'%>
        </div>
      </div>
  </div>
  </div>

  <div class="container">
    <%# = link_to "Leave a review", new_band_space_review_path(@bandspace.id) %>
    <% if @bandspace.user == current_user %>
    <div class="d-none">
    <% else %>
    <div data-controller="visibility">
    <button class="btn btn-flat" data-visibility-target="button" data-action="visibility#toggleTargets">
    <span data-visibility-target="span"> </span> new review form </button>
    <div id="new-review-form" data-visibility-target="hideable" hidden>
    <% end %>
    <%= render :partial => '/reviews/form'%>
    </div>
    <% @bandspace.reviews.each do |review| %>
    <div class="review-card">
      <p> <i class="fa-solid fa-user"></i> <%= review.user.username %></p>
      <div class="d-flex justify-content-between ">
        <h4> <%= review.title %></h3>
        <p> <i class="fa-solid fa-star"></i> <%= review.rating %> / 5 </p>
      </div>
      <p> <%= review.body %> </p>
    </div>
    <% end %>
  </div>
</div>
<div class="page-end"></div>

app/views/bandspaces/create.html.erb
<h1>Bandspaces#create</h1>
<p>Find me in app/views/bandspaces/create.html.erb</p>

app/views/bookings/_form.html.erb
  <%= simple_form_for [@bandspace, @booking] do |f| %>
    <%= f.input :date, as: :date, html5: true %>
    <%= f.submit "Create Booking", class: "btn btn-flat" %>

  <% end %>

app/views/bookings/confirmation.html.erb
<div class="container">
  <h1> Congratulations, your booking is complete</h1>
  <div class="booking-details">
    <h3> Venue: <%= @bandspace.name %></h3>
    <%= link_to "Back to homepage", band_spaces_path %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="text-center">
  <h1>Bandspace bookings for <%= @bandspace.name %></h1>
  <br>
    <%= link_to "Book this space!", new_band_space_booking_path %>
  <br>

  <%# we want to display all the bookings of a specific venu %>

  <%# we need to access the all the bookings of a specific venu %>
  <h2>The number of bookings are: <%= @bookings.count %></h2>
  <% @bandspace.bookings.each do |booking| %>
    <p><%= booking.id %>. <%= @bandspace.user.username %> </p>
  <% end %>





</div>

app/views/bookings/mine.html.erb
<div class="container col-9">
  <div class="header">
    <h1> My bookings </h1>
  </div>

  <% if @bookings.empty? %>
    <div class="body-container">
      <h3> You haven't made any bookings yet </h3>
    </div>
  <% else %>
    <div class="body-container">
      <% @bookings.each do |booking| %>
        <div class="card-product d-flex justify-content-between">
          <div class="d-flex">
            <div>
              <% if booking.band_space.photo_url.key %>
                <%=  cl_image_tag booking.band_space.photo_url.key, height: 300, width: 400, crop: :fill, class: "image" %>
              <% else  %>
                <img src=<%= booking.band_space.photo_url.record[:photo_url]%> style="height: 120;width: 120"%>
              <% end %>
            </div>
            <div class="card-product-infos d-flex flex-column justify-content-center">
              <h2> <%= booking.band_space.name %></h2>
              <p> <strong> <%= booking.date %> </strong> <p>
            </div>
          </div>
          <div>
            <%= link_to "See info", booking_path(booking), class: "btn btn-flat" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%= render "form", booking: @booking %>

app/views/bookings/show.html.erb
<div class="container booking col-6 shadow p-3 mb-5 bg-body rounded">
  <div class="space-header ">
    <h2> <%= @booking.band_space.name %> </h2>
  </div>
  <div class="host-capacity-price d-flex">
    <p> <%= @booking.band_space.rating %> <i class="fa-solid fa-star"></i></p>
    <p> Hosted by <strong> <%= @booking.user.username %> </strong> </p>
    <p> <i class="fa-sharp fa-solid fa-people-group"></i> Capacity: <strong><%= @booking.band_space.capacity %></strong> </p>
    <p> Price: <strong>£ <%= @booking.band_space.price %></strong> </p>
  </div>
  <% if @booking.band_space.photo_url.key %>
    <%=  cl_image_tag @booking.band_space.photo_url.key, height: 300, width: 400, crop: :fill, class: "image" %>
  <% else  %>
  <img src=<%= @booking.band_space.photo_url.record[:photo_url]%> style="height: 300;width: 400" class="image">
  <% end %>

  <div class="address-descrip ">
  <%#  link_to "Book this space", new_band_space_booking_path(@bandspace) %>
    <div class="booking-form my-1 p-1 ">
    </div>
    <p> <%= @booking.band_space.address %> </p>
    <p> <%= @booking.band_space.description %> </p>
    <h5> Date: <strong> <%= @booking.date %> </strong> </h5>
  </div>
  <div class="d-flex mb-1 pb-1">
    <div>
      <%= link_to "Back to Bookings", mine_bookings_path, class: "btn btn-flat" %>
    </div>
    <div>
      <%= link_to "Delete Booking", bookings_path(@booking), data: { turbo_method: :delete}, class: "btn" %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    ©Bandspaces
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="sticky-navbar">
  <div class="container-fluid">
      <%= link_to image_tag("https://i.pinimg.com/736x/c9/9b/27/c99b27b7ece4d9894ed490fb3529f0f5.jpg"), band_spaces_path %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-flat" %>
          </li>
          <li class="nav-item">
                <%= link_to "Sign in", new_user_session_path, class: "btn btn-flat" %>
          </li>
          <%# <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/120424620?v=4" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li> %>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navbarlivesession.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="sticky-navbar">
  <div class="container-fluid">
      <%= link_to image_tag("https://i.pinimg.com/736x/c9/9b/27/c99b27b7ece4d9894ed490fb3529f0f5.jpg"), band_spaces_path%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
             <h3 class="p-2"> Hi <%= current_user.username %>
          </li>
          <li class="nav-item active">
             <%= link_to "Bookings", mine_bookings_path, :method => :delete, :data => { :no_turbolink => true }, class: "btn btn-flat" %>
          </li>
           <li class="nav-item active">
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true }, class: "btn btn-flat" %>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BandSpaces</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% if user_signed_in?  %>
      <%= render "layouts/navbarlivesession" %>
    <% else %>
      <%= render "layouts/navbar" %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="body-container">
      <%= yield %>
    </div>
    <div class="make-footer">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80);">
  <div class="container">
    <h1>Find your ideal pratice space!</h1>
    <p>Browse thounsands of spaces uploaded by those in our community.</p>
    <%= link_to "Browse band spaces", band_spaces_path, class: "btn btn-flat" %>
  </div>
</div>

<div class="container m-3">
<div class="col-12 d-flex justify-content-center">
    <div class="row d-flex justify-content-evenly">
          <% @bandspaces.reverse.each do |bandspace| %>
            <div class="card" style="width: 18rem;">
            <% if bandspace.photo_url.key %>
              <%= cl_image_tag bandspace.photo_url.key, class: "card-img-top" %>
            <% else %>
              <img src="<%= bandspace.photo_url.record[:photo_url] %>" class="card-img-top" alt="...">
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to bandspace.name, band_space_path(bandspace), class: "text-decoration-none" %></h5>
              <p class="card-text"><%= bandspace.address %></p>
              <p class="card-text"> <strong>£ <%= bandspace.price%> </strong></p>
              <% if bandspace.rating == nil %>
                <p class="card-text"> <strong> No ratings </strong></p>
              <% else %>
                <p class="card-text"> <strong> <%= bandspace.rating%> / 5 </strong></p>
              <% end %>
            </div>
          </div>
          <% end  %>
        </div>
      </div>
    </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@bandspace, @review] do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :rating %>
    <%# change the input type to something better %>
  <%= f.submit "Submit review", class: "btn btn-flat" %>
<% end  %>

app/views/reviews/new.html.erb
<h1> Write you review </h1>

<%= simple_form_for [@bandspace, @review] do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :rating %>
    <%# change the input type to something better %>
  <%= f.submit "Submit review", class: "btn btn-flat" %>
<% end  %>